title: Obsidian-Selenium Plugin
description: A plugin to integrate selenium into obsidian

theme: just-the-docs
color_scheme: dark
logo: "/images/plugin.png"
favicon_ico: "/images/favicon.png"
button: true

url: https://smartguy1196.github.io/obsidian-selenium

aux_links:
  "View on GitHub":
    - "//github.com/smartguy1196/obsidian-selenium/docs/index.md"
  "Developers":
    - "//github.com/smartguy1196/obsidian-selenium/README.md"
